# ==============================================================
#
#  Intelligent Embedded Diagnostic System (IEDS)
#  Prometheus Configuration
#
# ==============================================================

global:

  scrape_interval: 5s

  evaluation_interval: 5s

# ==============================================================
#                      SCRAPE TARGETS
# ==============================================================

scrape_configs:

  # ============================================================
  #                      FASTAPI BACKEND
  # ============================================================

  - job_name: "ieds_backend"

    static_configs:

      - targets:
          - "backend:8000"

  # ============================================================
  #                      MQTT METRICS
  # ============================================================

  - job_name: "ieds_mqtt"

    static_configs:

      - targets:
          - "mqtt:1883"
